small-fixes
audio waits for hdmi switching now.
S31emulationstation waits when restarting
batocera-resolution improvements including board check for rg28xx

diff --git a/board/batocera/allwinner/h700/fsoverlay/usr/bin/batocera-resolution b/board/batocera/allwinner/h700/fsoverlay/usr/bin/batocera-resolution
--- a/board/batocera/allwinner/h700/fsoverlay/usr/bin/batocera-resolution
+++ b/board/batocera/allwinner/h700/fsoverlay/usr/bin/batocera-resolution
@@ -1,12 +1,12 @@
 #!/bin/sh
 
 DISPLAY="/sys/kernel/debug/dispdbg"
+HDMI_STATE="/sys/devices/platform/soc/6000000.hdmi/extcon/hdmi/state"
 
 f_usage() {
     echo "$0 listOutputs" >&2
     echo "$0 currentResolution" >&2
-	echo "$0 setOutput" >&2
-	echo "$0 currentOutput" >&2
+    echo "$0 setOutput" >&2
 }
 
 if [ $# -eq 0 ]; then
@@ -14,30 +14,55 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
+# use for syntax only
+PSCREEN=
+if test "${1}" = "--screen"
+then
+    shift
+    PSCREEN=$1
+    shift
+fi
+
 set_output() {
     OUTPUT=$1
     case "$OUTPUT" in
         hdmi)
-            # Set output for HDMI (720p external)
-			fbset -g 1 1 1 1 32
-			dd if=/dev/zero of=/dev/fb0 bs=4 count=1
-			echo disp0 > $DISPLAY/name
+            VIDEO=$(batocera-settings-get global.videooutput)
+            fbset -g 1 1 1 1 32
+            dd if=/dev/zero of=/dev/fb0 bs=4 count=1
+            echo disp0 > $DISPLAY/name
             echo switch1 > $DISPLAY/command
-            echo 4 5 0 0 0x4 0x201 0 1 0 8 > $DISPLAY/param
-			echo 1 > $DISPLAY/start
-			sleep 0.5
-            fbset -g 1280 720 1280 1440 32 -t 13468 220 40 20 5 110 5
+            if [ "$VIDEO" = "hdmi-480p" ]; then
+                echo 4 2 0 0 0x4 0x201 0 1 0 8 > $DISPLAY/param
+                echo 1 > $DISPLAY/start
+                sleep 0.5
+                fbset -g 640 480 640 960 32 -t 25175 40 24 32 9 96 2
+            elif [ "$VIDEO" = "hdmi-720p" ]; then
+                echo 4 5 0 0 0x4 0x201 0 1 0 8 > $DISPLAY/param
+                echo 1 > $DISPLAY/start
+                sleep 0.5
+                fbset -g 1280 720 1280 1440 32 -t 13468 220 40 20 5 110 5
+            elif [ "$VIDEO" = "hdmi-1080p" ] || [ "$VIDEO" = "" ]; then
+                echo 4 10 0 0 0x4 0x201 0 1 0 8 > $DISPLAY/param
+                echo 1 > $DISPLAY/start
+                sleep 0.5
+                fbset -g 1280 720 1280 1440 32 -t 13468 220 40 20 5 110 5
+            fi
             ;;
         internal)
-            # Set output for internal display (480p internal)
-			fbset -g 1 1 1 1 32
-			dd if=/dev/zero of=/dev/fb0 bs=4 count=1
-			echo disp0 > $DISPLAY/name
+            BOARD=$(cat /boot/boot/batocera.board)
+            fbset -g 1 1 1 1 32
+            dd if=/dev/zero of=/dev/fb0 bs=4 count=1
+            echo disp0 > $DISPLAY/name
             echo switch > $DISPLAY/command
             echo 1 0 > $DISPLAY/param
-			echo 1 > $DISPLAY/start
-			sleep 0.5
-            fbset -g 640 480 640 960 32 -t 13426 192 56 22 1 136 3
+            echo 1 > $DISPLAY/start
+            sleep 0.5
+            if [ "$BOARD" = "rg28xx" ]; then
+                fbset -g 480 640 480 1280 32 -t 13426 192 56 22 1 136 3
+            else
+                fbset -g 640 480 640 960 32 -t 13426 192 56 22 1 136 3
+            fi
             ;;
         *)
             f_usage
@@ -49,28 +74,36 @@ ACTION=$1
 
 case "${ACTION}" in
     "listOutputs")
+        echo "hdmi-1080p"
+        echo "hdmi-720p"
+        echo "hdmi-480p"
+        ;;
+    "listModes")
         ;;
     "setOutput")
-        HDMI_STATE="$(cat /sys/devices/platform/soc/6000000.hdmi/extcon/hdmi/state)"			
-		if [ "$HDMI_STATE" = "HDMI=1" ]; then  
-            set_output hdmi           			
-        else 
-			set_output internal
-		fi	
+        STATE=$(cat "$HDMI_STATE")
+        if [ "$STATE" = "HDMI=1" ]; then
+            set_output hdmi
+        else
+            set_output internal
+        fi
+        ;;
+    "currentResolution")
+        fbset | grep "geometry" | awk '{print $2"x"$3}'
         ;;
     "currentOutput")
         ;;
     "minTomaxResolution" | "minTomaxResolution-secure")
         ;;
-    "currentResolution")
-        fbset | grep "geometry" | awk '{print $2"x"$3}'
+    "supportSystemReflection")
+        exit 1
         ;;
     "supportSystemRotation")
         exit 1
         ;;
     *)
+        echo "error: invalid command ${ACTION}" >&2
         f_usage
-        >&2 echo "error: invalid command ${ACTION}"
         exit 1
         ;;
 esac
